spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/mercadolivro?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
    tomcat:
      driver-class-name: org.mariadb.jdbc.Driver